# yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json

vars:
  stage: prod

import:
  - catalog/station

components:
  terraform:
    example:
      vars:
        location: Los Angeles
        lang: en
