# yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json

vars:
  stage: dev

components:
  terraform:
    # Component with source provisioning
    myapp:
      source:
        uri: "github.com/cloudposse/terraform-null-label?ref=0.25.0"
      provision:
        workdir:
          enabled: true
      vars:
        enabled: true
        environment: "dev"
