# yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json

vars:
  stage: prod

components:
  terraform:
    # LOCAL source
    weather:
      source:
        uri: "../demo-library/weather"
      provision:
        workdir:
          enabled: true
      vars:
        location: "Los Angeles"

    # REMOTE source
    ipinfo:
      source:
        uri: "github.com/cloudposse/atmos//examples/demo-library/ipinfo"
        version: "main"
      provision:
        workdir:
          enabled: true
      vars:
        ip_address: "1.1.1.1"
