# yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json

vars:
  stage: prod

components:
  terraform:
    myapp:
      source:
        uri: "github.com/cloudposse/terraform-null-label?ref=0.24.1"
      provision:
        workdir:
          enabled: true
      vars:
        enabled: true
        environment: "prod"
